version: '2'
services:
  php-fpm:
    image: cdspscpo/quetelet-bdq:latest
    volumes:
      - ./quetelet-data/app-logs:/app/logs/
      - ./quetelet-data/app-data:/app/application/data/
    env_file:
      - ./quetelet-data/docker-app-variables.env
    links:
      - solr:solr
      - mysql:mysql
  solr:
    image: jrisp/solr-1.4:latest
    volumes:
      - ./quetelet-data/solr-index:/usr/local/tomcat/solr/solr/data
      - ./solr/conf:/usr/local/tomcat/solr/solr/conf
  mysql:
    image: mysql
    volumes:
      - ./quetelet-data/mysql-data/:/var/lib/mysql
      - ./quetelet-data/mysql-scripts/:/docker-entrypoint-initdb.d
    command: mysqld --sql_mode="" 
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes_from:
      - php-fpm:ro
    volumes:
      - ./nginx/bdq.reseau-quetelet.cnrs.fr.conf:/etc/nginx/conf.d/default.conf:ro 
    links:
      - php-fpm:php-fpm




