<?php 
$translate = Zend_Registry::get('translateAdmin');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title>R&eacute;seau Quetelet - Base de question</title>
		<?php  
			$this->headLink()->appendStylesheet('/css/admin.css');
			echo $this->headLink();
		?>
		<?php
			$this->headScript()->prependFile('/scripts/jqueryAndPlugins.js'); 
			echo $this->headScript();
		?>
		<script type="text/javascript" src="/scripts/dataTable.js"></script>
	</head>
	<body>
		<div id="header">
			<h1><?php echo $translate->_('BDQ - administration'); ?></h1>
			<?php echo $this->partial('admin-menu.phtml'); ?>
		</div>
		<div id="adminBody">
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>