<?php 
echo $this->doctype();
$clientSettings = BDQ_Settings_Client::getInstance();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
      	<?php echo $this->headMeta() ?>
		<title><?php echo isset($this->layout()->title) ? $this->layout()->title : 'Réseau Quetelet - Base de question'; ?></title>
		<?php 
      		echo $this->headLink()->appendStylesheet('/css/global.css');
      	?><link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
		<link rel="shortcut icon" type="image/png" href="/favicon.png" />
		<style type="text/css">
			body{width:<?php echo $clientSettings->bodySize; ?>;}
			#mainContainer{border-bottom:none;}
		</style>
	</head>
	<body>
		<?php echo $this->layout()->content; ?>
	</body>
</html>