<ul class="menu">
	<li>
		<a href="<?php 
	echo $this->url(
		array(),
		'nesstarserverAdd'
	);
?>" class="add"><?php echo $this->translate->_('fr0065000000') ?></a>
	</li>
</ul>
<?php
	if (count($this->nesstarservers) > 0):
?>
<table class="display" id="nesstarserver_index_table">
	<thead>
		<tr>
			<th><?php echo $this->translate->_('fr0065000010') ?></th>
			<th style="width:1%;"><?php echo $this->translate->_('fr0065000020') ?></th>
			<th class="action view"></th>
			<th class="action edit"></th>
			<th class="action delete"></th>
		</tr>
	</thead>
	<tbody>
<?php
	$i = 0;

	foreach ($this->nesstarservers as $nesstarserver):
?>
	<tr>
		<td>
			<?php 
				echo stripslashes($nesstarserver['title']);
			?>
		</td>
		<td>
			<?php 
				echo $nesstarserver['ddi_file_count'];
			?>
		</td>
		<td class="action">
			<a href="<?php 
	echo $this->url(
		array(
			'id' => $nesstarserver['id']
		),
		'nesstarserverView'
	);
	?>" class="view"><img src="/img/admin/view.png" alt="<?php echo $this->translate->_('fr0065000030'); ?>" title="<?php echo $this->translate->_('fr0065000040'); ?>"/></a>
		</td>
		<td class="action">
			<a href="<?php 
	echo $this->url(
		array(
			'id' => $nesstarserver['id']
		),
		'nesstarserverEdit'
	);
	?>" class="edit"><img src="/img/admin/edit.png"/ alt="<?php echo $this->translate->_('fr0065000050'); ?>" title="<?php echo $this->translate->_('fr0065000060'); ?>"/></a>
		</td>
		<td class="action">
			<a href="<?php 
	echo $this->url(
		array(
			'id' => $nesstarserver['id']
		),
		'nesstarserverConfirmdelete'
	);
?>" class="modal delete"><img src="/img/admin/delete.png" alt="<?php echo $this->translate->_('fr0065000070'); ?>" title="<?php echo $this->translate->_('fr0065000080'); ?>"/></a>
		</td>
	</tr>
<?php
		$i++;
	endforeach;
?>
	</tbody>
</table>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
	$("#nesstarserver_index_table").dataTable({
		"aaSorting": [[0, "asc"]],
		"oLanguage": {
			"sLengthMenu": "<?php echo $this->translate->_('fr0065000090'); ?>",
			"sZeroRecords": "<?php echo $this->translate->_('fr0065000100'); ?>",
			"sInfo": "<?php echo $this->translate->_('fr0065000110'); ?>",
			"sInfoEmpty": "<?php echo $this->translate->_('fr0065000120'); ?>",
			"sInfoFiltered": "<?php echo $this->translate->_('fr0065000130'); ?>",
			"sSearch" : "<?php echo $this->translate->_('fr0065000140'); ?>",
			"oPaginate":{
				"sPrevious": "&lt;<?php echo $this->translate->_('fr0065000150'); ?>",
				"sNext": "<?php echo $this->translate->_('fr0065000160'); ?>&gt;"
			}
		},
		"sPaginationType": "input",
		"aoColumns": [
		         		null,
		         		null,
		     			{ "bSortable": false, "bSearchable": false },
		     			{ "bSortable": false, "bSearchable": false },
		     			{ "bSortable": false, "bSearchable": false }
		     		],
		"bStateSave": true,
		"iCookieDuration": 36000000
	});
});
//]]>
</script>
<?php 
	endif;
?>
