<?php 
/**
 * Study facets
 * 
 * @author Xavier Schepler
 * @copyright Réseau Quetelet
 */
$translate = Zend_Registry::get('translateFront');
$clientSettings = BDQ_Settings_Client::getInstance();
?>
<li id="studyFacet">
	<?php 
	$this->facetGripStart();
	?>
	<span class="toggler<?php if ($clientSettings->studyFacetDisplay):?> down<?php endif;?>">&nbsp;</span>
	<span class="title"><?php echo $translate->_('fr0195000000');?></span>
	<?php 
	$this->facetGripEnd();
	?>
	<div class="toggled<?php if (empty($this->studyFacets)): ?> noResult<?php endif; ?>" <?php if ( ! $clientSettings->studyFacetDisplay):?> style="display:none;"<?php endif;?>>
		<?php 
		if ( ! empty($this->studyFacets)):
		?>
		<table class="filter" id="studyFilters" cellpadding="0" cellspacing="0">
			<thead>
				<tr>
					<th class="checkbox" title="<?php echo $translate->_('fr0195000050');

					?>">&nbsp;</th>
					<th class="title" title="<?php echo $translate->_('fr0195000100');

					?>">&nbsp;</th>
					<th class="count" title="<?php echo $translate->_('fr0195000150');

					?>">&nbsp;</th>
					<th class="invisible">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
			<?php
			$l = count($this->studyFacets);
			$showMore = false;
			
			for ($i = 0; $i < $l; $i += 3):
				$id = $this->studyFacets[$i];
				$study = $this->studyFacets[$i + 1];
				$count = $this->studyFacets[$i + 2];
				$checked = array_search($id, $this->studyFilters) !== false;
			?>
				<tr<?php if (($i / 3) >= MAX_FACETS_DISPLAY): ?> style="display:none;"<?php endif; ?>>
					<td class="checkbox">
						<input type="checkbox" id="studyCheckBox_<?php echo $id ?>" class="studyFilter resultFilter" name="studyFilters[]" value="<?php echo $id ?>"<?php if ($checked) { echo ' checked="checked"'; }?>/>
					</td>
					<td class="title">
						<label for="studyCheckBox_<?php echo $id ?>"><?php echo $study?></label>
					</td>
					<td class="count"></td>
					<td class="invisible">
						<?php echo normalize($study); ?>
					</td>
				</tr>
				
			<?php 
			endfor;
			?>
			</tbody>
		</table>
	<?php 
	endif;
	?>
	</div>
	<div class="clear"></div>
</li>