<h2><?php echo $this->translate->_('fr0215000000')?></h2>
<ul>
	<li>
		<a href="<?php echo $this->url(
				array(
				),
				'studyserieIndex'
			) ?>"><?php echo $this->translate->_('fr0215000010')?></a>
	</li>
	<li>
		<a href="<?php echo $this->url(
				array(
				),
				'studyserieView'
			) ?>"><?php echo $this->translate->_('fr0215000020')?></a>
	</li>
	<li>
		<a href="<?php echo $this->url(
				array(
				),
				'studyserieConfirmdelete'
			) ?>" class="modal"><?php echo $this->translate->_('fr0215000030')?></a>
	</li>
</ul>
<?php
echo $this->form;
?>
