<ul class="menu">
<li><a href="<?php 
	echo $this->url(
		array(),
		'studyserieAdd'
	);
?>" class="add"><?php echo $this->translate->_('fr0220000000') ?></a></li>
</ul>
<?php
	if (count($this->studyseries) > 0):
?>
<table class="display" id="studyserie_index_table">
	<thead>
		<tr>
			<th><?php echo $this->translate->_('fr0220000010') ?></th>
			<th style="width:1%;"><?php echo $this->translate->_('fr0220000020') ?></th>
			<th class="action view"></th>
			<th class="action edit"></th>
			<th class="action delete"></th>
		</tr>
	</thead>
	<tbody>
<?php
	$i = 0;

	foreach ($this->studyseries as $studyserie):
?>
	<tr>
		<td>
			<?php 
				echo $studyserie['title'];
			?>
		</td>
		<td>
			<?php 
				echo $studyserie['ddi_file_count'];
			?>
		</td>
		<td class="action">
			<a href="<?php 
echo $this->url(
	array(
		'id' => $studyserie['id']
	),
	'studyserieView'
);
	?>" class="view"><img src="/img/admin/view.png" alt="<?php echo $this->translate->_('fr0220000030'); ?>" title="<?php echo $this->translate->_('fr0220000040'); ?>"/></a>
		</td>
		<td class="action">
			<a href="<?php 
echo $this->url(
	array(
		'id' => $studyserie['id']
	),
	'studyserieEdit'
);
	?>" class="edit"><img src="/img/admin/edit.png"/ alt="<?php echo $this->translate->_('fr0220000050'); ?>" title="<?php echo $this->translate->_('fr0220000060'); ?>"/></a>
		</td>
		<td class="action">
			<a href="<?php 
echo $this->url(
	array(
		'id' => $studyserie['id']
	),
	'studyserieConfirmdelete'
);
?>" class="modal delete"><img src="/img/admin/delete.png" alt="<?php echo $this->translate->_('fr0220000070'); ?>" title="<?php echo $this->translate->_('fr0220000080'); ?>"/></a>
		</td>
	</tr>
<?php 
		$i++;
	endforeach;
?>
	</tbody>
</table>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
	$("#studyserie_index_table").dataTable({
		"aaSorting": [[0, "asc"]],
		"oLanguage": {
			"sLengthMenu": "<?php echo $this->translate->_('fr0220000090'); ?>",
			"sZeroRecords": "<?php echo $this->translate->_('fr0220000100'); ?>",
			"sInfo": "<?php echo $this->translate->_('fr0220000110'); ?>",
			"sInfoEmpty": "<?php echo $this->translate->_('fr0220000120'); ?>",
			"sInfoFiltered": "<?php echo $this->translate->_('fr0220000130'); ?>",
			"sSearch" : "<?php echo $this->translate->_('fr0220000140'); ?>",
			"oPaginate":{
				"sPrevious": "&lt;<?php echo $this->translate->_('fr0220000150'); ?>",
				"sNext": "<?php echo $this->translate->_('fr0220000160'); ?>&gt;"
			}
		},
		"sPaginationType": "input",
		"aoColumns": [
		         		null,
		         		null,
		     			{ "bSortable": false, "bSearchable": false },
		     			{ "bSortable": false, "bSearchable": false },
		     			{ "bSortable": false, "bSearchable": false }
		     		],
		"bStateSave": true,
		"iCookieDuration": 36000000
	});
});
//]]>
</script>
<?php 
	endif;
?>
